<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="homestyle.css">
  <meta name="theme-color" content="#daa37f">
  <title> Homepage</title>
</head>
<body>
  <div class="banner">
    <div class="banner__overlay">
      <div class="banner__container">
        <h1 class="banner__title">ArdaCiti Medicentre</h1>
          <p class="banner__text">A better way to practice care</p>
          <a href="index.php" class="survey_btn">Login</a>
      </div>
    </div>
  </div>
</body>